name: todo_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+5

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  timezone: ^0.9.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.2.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"

flutter_native_splash:
  color: "#EAEDF9"
  android_12:
    icon_background_color: "#EAEDF9"

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
